CRITICAL - 2022-06-14 23:24:20 --> Undefined variable: baris
#0 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(243): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 243, Array)
#1 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->hitung()
#2 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#3 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-14 23:24:26 --> Undefined variable: baris
#0 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(243): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 243, Array)
#1 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->hitung()
#2 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#3 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-14 23:24:31 --> Undefined variable: baris
#0 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(98): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->hitung()
#2 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#3 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-14 23:26:13 --> Undefined variable: baris
#0 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(243): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 243, Array)
#1 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->hitung()
#2 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#3 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-14 23:26:27 --> Division by zero
#0 C:\xampp\htdocs\event_organizer\app\Views\hitung.php(198): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Division by zer...', 'C:\\xampp\\htdocs...', 198, Array)
#1 C:\xampp\htdocs\event_organizer\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\event_organizer\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\event_organizer\system\Common.php(1089): CodeIgniter\View\View->render('hitung', Array, true)
#4 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(303): view('hitung', Array)
#5 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->hitung()
#6 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#7 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-06-14 23:26:58 --> Undefined variable: baris
#0 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(243): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 243, Array)
#1 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->hitung()
#2 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#3 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-14 23:29:48 --> Undefined variable: baris
#0 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(171): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 171, Array)
#1 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->hitung()
#2 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#3 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-06-14 23:32:52 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-06-14 23:32:52 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\event_organizer\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\event_organizer\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\event_organizer\app\Models\M_Alternatif.php(26): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(50): App\Models\M_Alternatif->findData('Hutan')
#4 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->cariTema('Hutan')
#5 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#6 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-06-14 23:32:52 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\event_organizer\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\event_organizer\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\ProsesAwal), true)
#2 C:\xampp\htdocs\event_organizer\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\event_organizer\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\event_organizer\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-06-14 23:33:02 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-06-14 23:33:02 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\event_organizer\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\event_organizer\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\event_organizer\app\Models\M_Alternatif.php(26): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(50): App\Models\M_Alternatif->findData('Gedung')
#4 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->cariTema('Gedung')
#5 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#6 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-06-14 23:33:02 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\event_organizer\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\event_organizer\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\ProsesAwal), true)
#2 C:\xampp\htdocs\event_organizer\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\event_organizer\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\event_organizer\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-06-14 23:33:11 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-06-14 23:33:11 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\event_organizer\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\event_organizer\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\event_organizer\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\event_organizer\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\event_organizer\app\Models\M_Alternatif.php(12): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\event_organizer\app\Controllers\ProsesAwal.php(29): App\Models\M_Alternatif->getAll()
#6 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(825): App\Controllers\ProsesAwal->index()
#7 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProsesAwal))
#8 C:\xampp\htdocs\event_organizer\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\event_organizer\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-14 23:33:11 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\event_organizer\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\event_organizer\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\ProsesAwal), true)
#2 C:\xampp\htdocs\event_organizer\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\event_organizer\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\event_organizer\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
